// LOADER
export const GENERAL_ENABLE_LOADER = 'GENEREAL_ENABLE_LOADER'
export const GENERAL_DISABLE_LOADER = 'GENEREAL_DISABLE_LOADER'

// GET LISTED JOBS
export const LISTED_JOBS_FETCH_REQUEST = 'LISTED_JOBS_FETCH_REQUEST'
export const LISTED_JOBS_FILTERED_FETCH_REQUEST = 'LISTED_JOBS_FILTERED_FETCH_REQUEST' //filtered
export const LISTED_JOBS_FETCH_RESPONSE = 'LISTED_JOBS_FETCH_RESPONSE'
export const LISTED_JOBS_FETCH_FAILURE = 'LISTED_JOBS_FETCH_FAILURE'
export const LISTED_JOBS_FETCH_REFRESH_RESPONSE = 'LISTED_JOBS_FETCH_REFRESH_RESPONSE'

// POST JOB
export const JOB_POST_REQUEST = 'JOB_POST_REQUEST'
export const JOB_POST_RESPONSE = 'JOB_POST_RESPONSE'
export const JOB_POST_FAILURE = 'JOB_POST_FAILURE'

// SAVE JOB
export const SAVE_JOB_REQUEST = 'SAVE_JOB_REQUEST'
export const UNSAVE_JOB_REQUEST = 'UNSAVE_JOB_REQUEST'
export const SAVE_JOB_RESPONSE = 'SAVE_JOB_RESPONSE'
export const SAVE_JOB_FAILURE = 'SAVE_JOB_FAILURE'

// GET SAVED JOBS
export const SAVED_JOBS_FETCH_REQUEST = 'SAVED_JOBS_FETCH_REQUEST'
export const SAVED_JOBS_FETCH_RESPONSE = 'SAVED_JOBS_FETCH_RESPONSE'
export const SAVED_JOBS_FETCH_FAILURE = 'SAVED_JOBS_FETCH_FAILURE'

// MY JOBS
export const FETCH_MY_JOBS_REQUEST = 'FETCH_MY_JOBS_REQUEST'
export const FETCH_MY_JOBS_RESPONSE = 'FETCH_MY_JOBS_RESPONSE'
export const FETCH_MY_JOBS_FAILURE = 'FETCH_MY_JOBS_FAILURE'

// FILTERS
export const CHANGE_FILTER_ITEMS = 'CHANGE_FILTER_ITEMS'
export const CLEAR_FILTER_ITEMS = 'CLEAR_FILTER_ITEMS'